### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by zas97** [DingLuoXMU/ConBAP#3]
Which python version works for the project? Tried it with 3.12 and it cannot install numpy.

**Comment by ld139** [comment]
python==3.8.16

**Comment by pycode-10** [comment]
This might be due to compatibility issue. Try using python 3.10

**Comment by zas97** [comment]
It sure is, gonna go with 3.8.16 and write all install steps once it works

**Comment by zas97** [comment]
Okey, so installation is a lot harder than whats written in the readme, @DingLuoXMU I recommend to update readme with the following:

Install python 3.8.16 using conda
with conda install:
pytorch==2.2 (see in pytorch official website instructions, i installed with cuda 12.1, https://pytorch.org/get-started/locally/)
pymol-open-source==2.5.0

Install GVP-GNN:
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-2.2.0+cu121.html 
follow instructions here: https://github.com/drorlab/gvp-pytorch
git clone https://github.com/drorlab/gvp-pytorch.git
cd gvp-pytorch
pip install -e .

Finally the rest of dependencies (copy it in a requirements.txt and run pip install -r requirements.txt):
matplotlib==3.7.2
networkx==3.1
numpy==1.24.3
pandas==2.0.3
rdkit==2022.09.5
scikit_learn==1.3.0
scipy==1.5.2
seaborn==0.12.2
tqdm==4.63.0
biopython==1.78

For the moment I tested this setup only on cpu and doing inference, will report any problem if it doesn't work for training or gpu inference.

**Comment by ld139** [comment]
> Okey, so installation is a lot harder than whats written in the readme, @DingLuoXMU I recommend to update readme with the following:
> 
> Install python 3.8.16 using conda with conda install: pytorch==2.2 (see in pytorch official website instructions, i installed with cuda 12.1, https://pytorch.org/get-started/locally/) pymol-open-source==2.5.0
> 
> Install GVP-GNN: pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-2.2.0+cu121.html follow instructions here: https://github.com/drorlab/gvp-pytorch git clone https://github.com/drorlab/gvp-pytorch.git cd gvp-pytorch pip install -e .
> 
> Finally the rest of dependencies (copy it in a requirements.txt and run pip install -r requirements.txt): matplotlib==3.7.2 networkx==3.1 numpy==1.24.3 pandas==2.0.3 rdkit==2022.09.5 scikit_learn==1.3.0 scipy==1.5.2 seaborn==0.12.2 tqdm==4.63.0 biopython==1.78
> 
> For the moment I tested this setup only on cpu and doing inference, will report any problem if it doesn't work for training or gpu inference.

yes! Thank you for your patience!

**Comment by zas97** [comment]
thanks for open sourcing the code =)
